### PR TITLE
Added simple Bidder registration screen (1.0)

### PR DESCRIPTION
**Pull request by medeirosT**

### CODE REVIEW

**Comment by Mystro256** [comment]
It should automatically add commits if the pull request is against master.

Anyway, I'll take a look-see tonight, thanks!

**Comment by Mystro256** [comment]
Do you mind squashing 6f95127 and 7357bd7, just to clean it up it when I pull it in?

**Comment by meaganhanes** [comment]
Why am I being notified for these :)

**Comment by Mystro256** [comment]
You're currently watching this repo. Click unwatch at the top.

**Pull request merged**
